DrilldownGraph/objects/Sales_products__c/Sales_products__c.object-meta.xml
<CustomObject>
    <label>Sales products</label>
    <nameField>
        <label>Sales products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DrilldownGraph/objects/Sales_products__c/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Clothing</fullName>
            </value>
            <value>
                <fullName>Electronics</fullName>
            </value>
            <value>
                <fullName>Home Goods</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

DrilldownGraph/objects/Sales_products__c/fields/Product_Price__c.field-meta.xml
<CustomField>
    <fullName>Product_Price__c</fullName>
    <label>Product Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

DrilldownGraph/objects/Sales_products__c/fields/Sold_Date__c.field-meta.xml
<CustomField>
    <fullName>Sold_Date__c</fullName>
    <label>Sold Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

DrilldownGraph/classes/DrillDownGraphController.cls
public with sharing class DrillDownGraphController {
    @AuraEnabled(cacheable=true)
    public static List<AggregateResult> getSalesByQuater() {
      return [
        SELECT Product_Category__c, CALENDAR_QUARTER(Sold_Date__c) Quarter__c, SUM(Product_Price__c) Total_Sales__c
        FROM Sales_products__c
        GROUP BY Product_Category__c, CALENDAR_QUARTER(Sold_Date__c) 
       ];
    }
    @AuraEnabled
    public static List<AggregateResult> getSalesByMonth( Integer quarter) {
        List<AggregateResult> results = [
            SELECT Product_Category__c, CALENDAR_MONTH(Sold_Date__c) month, SUM(Product_Price__c) Total_Sales
            FROM Sales_products__c
            WHERE CALENDAR_QUARTER(Sold_Date__c) = :quarter
            GROUP BY Product_Category__c, CALENDAR_MONTH(Sold_Date__c)
        ];

        return results;
      }

  }